workflows:
    ios-swiftly:
      name: ios_swiftly
      environment:
        vars:
          XCODE_WORKSPACE: "swiftly.xcworkspace" # <-- Put the name of your workspace here. 
          XCODE_SCHEME: "swiftly" # <-- Put the name of your scheme here.
          # Set up env vars for manual codesigning (See - https://docs.codemagic.io/code-signing-yaml/signing-ios/)
          CM_CERTIFICATE: Encrypted(...) # <-- Put your encrypted distribution certificate here. 
          CM_CERTIFICATE_PASSWORD: Encrypted(...) # <-- Put your encrypted distribution certificate password here.
          CM_PROVISIONING_PROFILE: Encrypted(...) # <-- Put your encrypted provisioning profile here.
        xcode: latest
        cocoapods: default
      triggering:
        events:
          - push
          - tag
          - pull_request
        branch_patterns:
          - pattern: 'master'
            include: true
            source: true
      scripts:
        - xcodebuild build -project "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        email:
            recipients:
              - user1@example.com
              - user2@example.com
            notify:
              success: true
              failure: true
        app_store_connect:                 
            apple_id: yourAppleId@example.com  # <- Put your Apple Id here
            password: Encrypted(...) # <-- Put your Encrypted App-specific Password here (use the Codemagic Webapp to do this). For more information visit: https://support.apple.com/en-us/HT204397
    
      
